function output     = cutoffs_10Jun2026(par, par_star, parL, parH, parL_star, parH_star, conjectures)


% Read-in the conjectured objects (Q, C, C_star, wHl wHh wLl wLh wHl_star wHh_star wLl_star wLh_star psiL psiH psiL_star psiH_star)
Q           = conjectures(1);
C           = conjectures(2);
C_star      = conjectures(3);
wHl         = conjectures(4);
wHh         = conjectures(5);
wLl         = conjectures(6);
wLh         = conjectures(7);
wHl_star    = conjectures(8);
wHh_star    = conjectures(9);
wLl_star    = conjectures(10);
wLh_star    = conjectures(11);
psiL        = conjectures(12);
psiH        = conjectures(13);
psiL_star   = conjectures(14);
psiH_star   = conjectures(15);

% The North offshoring cutoffs
% z_VL checked
z_VL            = ((parL.fV*(Q/par_star.Z)*(wLl_star/(1-parL.alpha))^(1-parL.alpha)*(wLh_star/parL.alpha)^(parL.alpha))/ ...
    ((1/(psiL^(1-par.theta)))*(1/par.theta)*(par.theta/(par.theta-1))^(1-par.theta)*parL.gamma*C* ...
    (((parL.tau_offshoring*Q*wLl_star)/(par_star.Z*(1-parL.alpha)))^((1-parL.alpha)*(1-par.theta))* ...
    (wLh/(par.Z*parL.alpha))^(parL.alpha*(1-par.theta)) - ((1-parL.s_D)/par.Z)^(1-par.theta)*(wLl/(1-parL.alpha))^((1-parL.alpha)*(1-par.theta))* ...
    (wLh/parL.alpha)^(parL.alpha*(1-par.theta)))))^(1/(par.theta-1));
% checked
z_VH            = ((parH.fV*(Q/par_star.Z)*(wHl_star/(1-parH.alpha))^(1-parH.alpha)*(wHh_star/parH.alpha)^(parH.alpha))/ ...
    ((1/(psiH^(1-par.theta)))*(1/par.theta)*(par.theta/(par.theta-1))^(1-par.theta)*parH.gamma*C* ...
    (((parH.tau_offshoring*Q*wHl_star)/(par_star.Z*(1-parH.alpha)))^((1-parH.alpha)*(1-par.theta))* ...
    (wHh/(par.Z*parH.alpha))^(parH.alpha*(1-par.theta)) - ((1-parH.s_D)/par.Z)^(1-par.theta)*(wHl/(1-parH.alpha))^((1-parH.alpha)*(1-par.theta))* ...
    (wHh/parH.alpha)^(parH.alpha*(1-par.theta)))))^(1/(par.theta-1));

% The North exporting cutoffs
% checked
z_XL            = (((parL.fX/par.Z)*((wLl/(1-parL.alpha))^(1-parL.alpha))*((wLh/parL.alpha)^parL.alpha))/ ...
    ((1/(psiL_star^(1-par.theta)))*(1/par.theta)*((1+parL_star.tauIM)^(-par.theta))*((par.theta/(par.theta-1))* ...
    (parL.tau*(Q^(-1))/par.Z)*((wLl/(1-parL.alpha))^(1-parL.alpha))*((wLh/parL.alpha)^parL.alpha))^(1-par.theta) ...
    *parL.gamma*C_star*Q))^(1/(par.theta-1));

% checked
z_XH            = (((parH.fX/par.Z)*((wHl/(1-parH.alpha))^(1-parH.alpha))*((wHh/parH.alpha)^parH.alpha))/ ...
    ((1/(psiH_star^(1-par.theta)))*(1/par.theta)*((1+parH_star.tauIM)^(-par.theta))*((par.theta/(par.theta-1))* ...
    (parH.tau*(Q^(-1))/par.Z)*((wHl/(1-parH.alpha))^(1-parH.alpha))*((wHh/parH.alpha)^parH.alpha))^(1-par.theta) ...
    *parH.gamma*C_star*Q))^(1/(par.theta-1));

% The South offshoring cutoffs
% checked
z_VL_star        = (((parL_star.fV*(Q^(-1))/par.Z)*((wLl/(1-parL.alpha))^(1-parL.alpha))*((wLh/parL.alpha)^parL.alpha))/ ...
    ((1/(psiL_star^(1-par.theta)))*(1/par.theta)*((par.theta/(par.theta-1))^(1-par.theta))* ...
    ((wLl_star/(par_star.Z*(1-parL.alpha)))^((1-parL.alpha)*(1-par.theta))*...
    ((parL_star.tau_offshoring*(Q^(-1))*wLh)/(par.Z*parL.alpha))^(parL.alpha*(1-par.theta)) ...
    - (((1-parL_star.s_D)/par_star.Z)^(1-par.theta))*((wLl_star/(1-parL.alpha))^ ...
    ((1-parL.alpha)*(1-par.theta)))*((wLh_star/parL.alpha)^(parL.alpha*(1-par.theta))))*parL.gamma*C_star))^ ...
    (1/(par.theta-1));

% checked
z_VH_star        = (((parH_star.fV*(Q^(-1))/par.Z)*((wHl/(1-parH.alpha))^(1-parH.alpha))*((wHh/parH.alpha)^parH.alpha))/ ...
    ((1/(psiH_star^(1-par.theta)))*(1/par.theta)*((par.theta/(par.theta-1))^(1-par.theta))* ...
    ((wHl_star/(par_star.Z*(1-parH.alpha)))^((1-parH.alpha)*(1-par.theta))*...
    ((parH_star.tau_offshoring*(Q^(-1))*wHh)/(par.Z*parH.alpha))^(parH.alpha*(1-par.theta)) ...
    - ((1-parH_star.s_D)/par_star.Z)^(1-par.theta)*((wHl_star/(1-parH.alpha))^ ...
    ((1-parH.alpha)*(1-par.theta)))*((wHh_star/parH.alpha)^(parH.alpha*(1-par.theta))))*parH.gamma*C_star))^ ...
    (1/(par.theta-1));

% The South exporting cutoff
% checked
z_XL_star        = (((parL_star.fX/par_star.Z)*((wLl_star/(1-parL.alpha))^(1-parL.alpha))*((wLh_star/parL.alpha)^parL.alpha))/ ...
    ((1/(psiL^(1-par.theta)))*(1/par.theta)*((1+parL.tauIM)^(-par.theta))*(((par.theta/(par.theta-1))* ...
    (parL_star.tau*Q/par_star.Z)*((wLl_star/(1-parL.alpha))^(1-parL.alpha))*((wLh_star/parL.alpha)^parL.alpha))^(1-par.theta)) ...
    *parL.gamma*C*Q^(-1)))^(1/(par.theta-1));

% checked
z_XH_star        = (((parH_star.fX/par_star.Z)*((wHl_star/(1-parH.alpha))^(1-parH.alpha))*((wHh_star/parH.alpha)^parH.alpha))/ ...
    ((1/(psiH^(1-par.theta)))*(1/par.theta)*((1+parH.tauIM)^(-par.theta))*(((par.theta/(par.theta-1))* ...
    (parH_star.tau*Q/par_star.Z)*((wHl_star/(1-parH.alpha))^(1-parH.alpha))*((wHh_star/parH.alpha)^parH.alpha))^(1-par.theta)) ...
    *parH.gamma*C*Q^(-1)))^(1/(par.theta-1));




output(1)       = z_VL;
output(2)       = z_VH;
output(3)       = z_XL;
output(4)       = z_XH;
output(5)       = z_VL_star;
output(6)       = z_VH_star;
output(7)       = z_XL_star;
output(8)       = z_XH_star;




end